### ISSUE TITLE
No longer working!

### ISSUE THREAD

**Issue by anhkind** [bachvtuan/Download-album-from-chiasenhac.com#2]
Hi, can you help check if the script is sill working good? My command is as following and it won't work:

```
 casperjs --disk-cache=true collect.js http://chiasenhac.vn/nghe-album/london-bridge~fergie~tsvqwt0dqe9fnm.html foo bar && python download.py 320 ~/Desktop/The-Dutchess
```

**Comment by bachvtuan** [comment]
Indeed,I think this code isn't updated for a long time since the website changed a lot. I'll check when I'm free.

**Comment by anhkind** [comment]
Thanks.

**Comment by bachvtuan** [comment]
Hi, I opened a investigate and found out that new CASPERJS changed some methods, Please update new code with recommended CASPERJS and PHANTOMJS to make sure it work.

**Comment by anhkind** [comment]
Hey @bachvtuan, it's working AWESOME! Thank you for the great effort! Cheers 👍
